### PR TITLE
Sp5 css fix next step

### PR DESCRIPTION
**Pull request by mayard689**

### CODE REVIEW

**Review by Emmanuelle-Mendels — DISMISSED** [review]
ok

**Review by ldupas — DISMISSED** [review]
Fix ok.

**Comment by mayard689** [comment]
ok

**Review by ldupas — DISMISSED** [review]
ok

**Review by Emmanuelle-Mendels — APPROVED** [review]
ok

**Review by ldupas — APPROVED** [review]
ok

**Pull request merged**
