### PR TITLE
SP4US42_EditActivityWithPictureUpload

### PR DESCRIPTION
**Pull request by mayard689**
US42 - Add picture upload

### CODE REVIEW

**Review by Emmanuelle-Mendels — DISMISSED** [review]

**Review by mayard689 — COMMENTED** [review]
Removes unwanted var_dump and commented code

**Review by ldupas — APPROVED** [review]
Picture Upload ok.

**Comment by ldupas** [comment]
Il manque une validation.

**Review by Emmanuelle-Mendels — APPROVED** [review]
ok

**Pull request merged**
